config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { passwords: 'users/passwords', registrations: 'users/registrations' }
  get '/withdraw', to: 'transactions#withdraw'
  get '/transfer', to: 'transactions#transfer'
  get '/deposit', to: 'transactions#deposit'
  resources :transactions, only: [:create, :index]
  resources :cards, only: [:create]
  resources :accounts, only: [:create]

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/views/layouts/_user_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home',root_path, class: 'nav-link' %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Money Management
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Deposit Money',deposit_path, class: 'dropdown-item' %>
          <%= link_to 'Withdraw Money', withdraw_path  , class: 'dropdown-item' %>
          <%= link_to 'Transfer Money',transfer_path, class: 'dropdown-item' %>
        </div>
      </li>
      </li>
      <li class="nav-item">
        <%= link_to 'View Transaction',transactions_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <% if current_user.present? %>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
            <li><%= link_to 'LogIn / Register', new_user_session_path, class: 'nav-link' %></li>
        <% end %>
      </li>
      <% if current_user.present? %>
        <span class="account_number">Account No: <%= current_user.account.acc_number %></span>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AccountApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>